name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bugfix'
  - title: '🧰 Maintenance'
    label: 'chore'
template: |
  ## Changes

  $CHANGES

